# Generated by Django 2.2.8 on 2019-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('fullname',), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(auto_now=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Nation'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Page Size'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
